apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: juiceshop
  title: Juiceshop
  description: |
    Payment Application for our company
  labels:
    tier: "3"
  tags:
    - test
    - js
    - demo
  annotations:
    github.com/project-slug: somerset-inc/juice-shop-goof
spec:
  type: service
  owner: group:somerset-inc/cs-goof-back-end
  lifecycle: production
  system: JuiceShop-Payment-App
  providesApis:
    - juice-shop-goof
  dependsOn:
    - Component:juice-shop-goof-2
    - Resource:sample-s3-bucket
